---
title: "Research"
---

## Journal Articles 
1. Forum, B. M. (2026). Bureaucratic Turnover Under New Governments: The Moderating Effect of Bureaucratic and Political Layering. *Journal of Public Administration Research and Theory*, 36(4), 429-446. doi: [10.1093/jopart/muag016](https://doi.org/10.1093/jopart/muag016){target="_blank"}

## Book Chapters
1. Forum, B. M. (2027). Norway: Two Career Paths in a Dyadic Executive Structure. In *The Palgrave Handbook of Careers in the Executive Triangle*, edited by Jan-Hinrik Meyer-Sahling, Tom Bellens, Anne Bellon, Levent Demirelli, Pierre Squevin, Fanni Tóth, Sylvia Veit, and Kutsal Yesilkagit. Palegrave. [PDF here](Forum_NORWAY_COREX_WG2_country_chapter_revised_2026-02-27_FINAL.pdf){target="_blank"}

2. Rasch, B.E., Forum B. M. & Bucur C. (2026). Parliamentary institutions and portfolio allocation in coalition governments. In *Democracy at the Crossroads – Challenges for Governance and Representation: Essays in Honour of Thomas Saalfeld*, edited by Jorge M. Fernandes and Javier Martínez-Cantó. Routledge. doi: [10.4324/9781003660248-18](https://doi.org/10.4324/9781003660248-18){target="_blank"}

3. Bach, T., Forum, B. M., & Hesstvedt, S. (2025). Norway: Formal and informal politicization in a merit bureaucracy. In *Handbook of Politicization and Political Patronage*, edited by B. Guy Peters, Colin Knox, Francesco Panizza, Conrado Ramos, and Katarína Staroňová. Edward Elgar Publishing. doi: [10.4337/9781035326242.00012](https://www.elgaronline.com/abstract/book/9781035326242/chapter5.xml){target="_blank"}

4. Askim, Jostein; Forum, Bjørn Mo & Tranøy, Bent Sofus (2024). The party politics of policy endurance: parliamentary settlements in Norway, 1980-2021. In *Pathways to Positive Public Administration*, edited by Patrick Lucas, Tina Nabatchi, Janine O’Flynn, and Paul 't Hart. Edward Elgar Publishing. doi: [10.4337/9781803929170.00034](https://doi.org/10.4337/9781803929170.00034){target="_blank"}


## Working Papers
1. Askim, J., Forum, B. M., & Høyland, B. Pattern of Deliberation in Norwegian Cabinet Conferences 1945–1985.

2. Forum, B.M. When Does the Cabinet Constrain the Minister? Evidence from Cabinet Deliberations on Bureaucratic Appointments in Norway 1945-1985. (Presented at EGPA 2025, ECPR 2026)

3. Forum, B. M. & Hesstvedt, S. Party Representation on Government Advisory Commissions. [Version presented at Nasjonal Fagkonferanse i Statsvitenskap 2026](Forum_Hesstvedt_Party-representation-on-commissions_Fagkonferansen2026.pdf){target="_blank"}

4. Forum, B. M., Askim, J., & Mangset, M. Constraining the Prince: The Architecture of Merit-Based Recruitment. (Under review) [Version presented at EGPA 2025](Forum_Askim_Mangset_EGPA 2025.pdf){target="_blank"}

## Master’s Thesis
- Forum, B. M. (2022). The Political Dynamics of Administrative Turnover: The effects of political change on the careers of top civil servants in Norwegian ministries 1884-2021 [Master’s Thesis, Universitetet i Oslo](Forum_Bj-rn_Master.pdf){target="_blank"}. http://urn.nb.no/URN:NBN:no-98325
