---
title: "Langsiktig politikk i andre rekke: er de brede forlikenes tid forbi?"
description: "Ap er negative til forlik i Stortinget. Når reverseringsviljen er høy, bør regjeringer vokte seg for å vedta politikk på knappest mulig flertall."
author: "Bjørn Mo Forum"
date: "2024-11-04"
categories:
  - Stortingsforlik
  - Skatteforlik
  - Norsk politikk
  - Stortinget
---

*Ap er negative til forlik i Stortinget. Når reverseringsviljen er høy, bør regjeringer vokte seg for å vedta politikk på knappest mulig flertall.*

<span style="color:grey;"> Denne teksten ble først utarbeidet til eksamen i emnet SV9106 (UiO)</span>

## Forlik – ikke lenger «et mål i seg selv»

Finanspolitisk talsperson for både [Ap](https://www.aftenposten.no/norge/politikk/i/onJ41W/aps-ferske-finanstopp-freder-hver-krone-fra-formuesskatten){target="_blank"} og [Høyre](https://e24.no/norsk-oekonomi/i/nyL16L/skattesystemet-maa-staa-seg-over-tid){target="_blank"} har i sommer uttalt seg som om hva deres partier mener om endringer i skattesystemet. 
Mens Aps Tuva Moflag ikke ønsker å stenge døren helt for et skatteforlik med Høyre, utaler hun likevel at: «et forlik er ikke et mål i seg selv. Det er viktigere for oss at vi har et skattesystem som er effektivt, omfordelende og rettferdig enn å få til et skatteforlik med Høyre.»

Evnen til å søke samarbeid og oppnå kompromisser på tvers av politiske skillelinjer i sentrale politiske stridsspørsmål hvor langsiktighet og stabilitet er ønskelig har vært en sentral del av norsk politikk. Noe også Høyres Tina Bru anerkjenner i sitt tilsvar til Moflag. Samtidig illustrerer Bru godt hvorfor bred enighet er viktig for stabilitet når hun lover å reversere skatter denne regjeringen innfører med minste vinnende flertall neste gang borgerlig side vinner flertall i Stortinget.

## Forlik som instrument for å komponere langsiktig politikk
Sammen med Jostein Askim (UiO) og Bent Sofus Tranøy (HINN) har jeg [forsket](https://doi.org/10.4337/9781803929170.00034){target="_blank"} på og kartlagt bruken av brede politiske forlik i Stortinget de siste 40 årene. Selv om ordet forlik har blitt et moteord for stortingspolitikere – i seneste tid også brukt om avtaler mellom regjeringen og dens typiske støttepartier, slik som [pelsdyrforliket](https://www.vg.no/nyheter/i/wPmP74/enighet-mellom-frp-og-regjeringen-dette-er-pelsdyrforliket){target="_blank"} mellom Solberg-regjeringen og Frp – mener vi at forlik som har som formål å skape stabilitet skiller seg fra vanlige stortingsvedtak på 2 måter: antall partier og en offentlig kommunisert avtale mellom dem. 

Når det kommer til antall partier har partiene i Stortinget normalt insentiver til å danne et minste-vinnende flertall, det vil si at de ønsker å danne en gruppe med så få partier som mulig for å komme over flertallsgrensen på 50% av stortingsrepresentantene, i hver sak. Dette gjør at partiene som er en del av flertallet får et utfall som er så nærme som mulig deres primærstandpunkt dersom de kunne bestemt alene, uten at de må gi fra seg noe til partiene som ikke er nødvendige for å få flertall.

Forlik skiller seg fra normalen ved at flertallet som dannes er overtallig, det vil si består av flere partier enn det som er nødvendig for å få flertall. Siden det utalte formålet med forlik er stabilitet legger vi også vekt på at avtalen må omfatte de to mest sentrale styringspartiene på borgerlig og sosialistisk side, nemlig Ap og Høyre.

For å skille fremforhandlede forlik fra tilfeller hvor partienes primærstandpunkter rett og slett sammenfaller har vi også lagt vekt på at partiene selv omtaler enigheten som et forlik i offentligheten.

## Forliksinstituttet i et historisk perspektiv
Totalt fant vi 21 forlik i perioden 1980-2021. Dette innebærer ca. ett forlik per andre år. Forlikene dekker politikkområder av langsiktig nasjonal betydning hvor partiene ofte har sterke primærstandpunkter; som sikkerhetspolitikk, klimatiltak, etableringen av oljefondet, adskillelsen av kirke og stat, samt skattesystem for å nevne noen.

Det typiske forliket har sine røtter i en stortingsmelding eller proposisjon fra regjeringen, fremmes rundt midten av en stortingsperiode og fremforhandles gjerne mens saken er til behandling i Stortingets komiteer. 12 av forlikene vi har kartlagt kom under borgerlige regjeringer, mens sosialistiske regjeringer produserte 9 forlik.

Historisk sett har det primært vært partiene til venstre for Ap og til høyre for Høyre som har deltatt i færrest forlik.

Brødparten av forlikene fant sted mellom 2001 og 2016. Under Solberg regjeringens andre periode var det eneste vellykkede forliket krisedrevet knyttet til [midlertidig skattelettelse for petroleumssektoren under pandemien](https://www.nrk.no/norge/slik-blir-endringene-i-oljeskatten-1.15044882){target="_blank"}, og Støre-regjeringen har likeledes produsert et sikkerhetspolitisk viktig forlik om [støtte til Ukraina](https://www.stortinget.no/no/Saker-og-publikasjoner/Saker/Sak/Voteringsoversikt/?p=92976&dnid=1){target="_blank"}.

Når det kommer til hvorvidt forlik er vellykkede instrumenter for å komponere politikk som varer over tid finner vi at de fleste forlik blir videreført av fremtidige regjeringer. Det eneste tilfellet hvor en regjering har ønsket å reversere deler av et forlik er «nærpolitireformen» fra 2015. 

## Er forlikenes tid forbi?
Man kan argumentere for at forliksinstitusjonen har vært i tilbakegang fra omtrent tidspunktet for politireformen i 2015. De forlikene som har blitt inngått siden den gang, har på sett og vis vært lavt hengende frukter; de har dreid seg om regjeringens svar på midlertidige kriser og videreføringen av et rovviltforlik som opprinnelig ble fremforhandlet av tidligere regjeringer. 

Samtidig har det vært flere forsøk på å produsere nye forlik som har falt igjennom de seneste årene, det har blant annet vært snakk om forlik om havvind, strøm og barnehagepolitikk som ikke har materialisert seg. Forsøket på å fremforhandle et tredje klimaforlik i 2021 endte med et «[politisk mageplask](https://www.nrk.no/norge/intet-klimaforlik-pa-stortinget-_-opposisjonen-reagerer-1.15431857){target="_blank"}» for å bruke ordene til daværende MDG leder Une Bastholm.

Denne dragningen vekk fra normer og tradisjoner for kompromissdannelse i politikken er ikke typisk norsk, den føyer seg inn i en [trend på tvers av demokratiske systemer](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1468-0491.2012.01569.x){target="_blank"} med en mer polarisert partipolitisk kultur. Hvor vellykket langsiktig politikk tuftet på kompromisser taper terreng til fordel for kortsiktige politikk tuftet på varierende flertall, motivert av mål om valgseire og kortsiktige gevinster. Vellykket langsiktig politikk kommer i andre rekke.

## Er brede forlik udemokratisk?
Kanskje er ikke dette et så negativt utviklingstrekk i demokratisk sammenheng? Forliksinstituttet kan på den ene siden roses for at også opposisjonspartiene tar ansvar for langsiktige beslutninger. På den andre siden kan det også kritisert for å være politisk ansvarsfraskrivelse fra regjeringen, hvor støtten fra både regjeringspartier og opposisjonspartier gjør det nærmest umulig for velgerne å rettmessig plassere skyld for feilslåtte reformer. 

I [Danmark](https://ps.au.dk/fileadmin/Statskundskab/Billeder/Forskning/Forskningsprojekter/Magtudredning/Essays/Tema2/Essay1_Flemming_Juul_Christiansen.pdf){target="_blank"} kritiseres bruken av forliksavtaler ofte for å flytte politikkdannelsen ut av Folketinget og over til elite-politikere på bakrommet. I Norge er derimot forhandlingene om inngåelsen av forlikene mer åpne gjennom Stortingskomiteenes innstillinger og påfølgende debatt, hvor ikke bare enigheten, men også partienes primære standpunkter blir løftet frem i mindretallsmerknader og alternative forslag.

## Forlik bør noen ganger være et mål i seg selv
Til slutt er det verdt å nevne at også politikk tuftet på knappe flertall kan vedvare, hvis det er god politikk som flertallet i befolkningen ønsker over tid, bare se til f.eks. handlingsregelen og sykehusreformen. Men, å bygge store langsiktige reformer på knappe flertall kan fort bli en kostbar oppskrift når politiske vinder snur slik vi har sett med Støre regjeringens reversering av Solberg regjeringens kommunesammenslåinger. Forlik bør ikke alltid være et mål i seg selv, men når reverseringsviljen er høy bør regjeringer vokte seg for å vedta politikk på knappest mulig flertall.
